name       : neovim-qt
version    : 0.2.10
release    : 3
source     :
    - https://github.com/equalsraf/neovim-qt/archive/v0.2.10.tar.gz : 42e3205f3fa9924e4970aed8ff28d17d9aefeb394bb40493d37f8a0afba40c34
license    : ISC
component  : editor
summary    : Neovim client library and GUI, in Qt5.
description: |
    Neovim client library and GUI, in Qt5.
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(msgpack)
    - pkgconfig(Qt5Widgets)
    - neovim
rundeps    :
    - neovim
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_MSGPACK=ON .
build      : |
    %make
install    : |
    %make_install
