name       : neovim-qt
version    : 0.2.8
release    : 1
source     :
    - https://github.com/equalsraf/neovim-qt/archive/v0.2.8.tar.gz : 53653c21de1dd41fb78a65f27e989b3478c74ad91cbde92f831fb3d81b25802b
license    : ISC
component  : editor
summary    : Neovim client library and GUI, in Qt5.
description: |
    Neovim client library and GUI, in Qt5.
rundeps    :
    - neovim
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(msgpack)
    - neovim
    - pkgconfig(Qt5Widgets)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_MSGPACK=ON .
build      : |
    %make
install    : |
    %make_install
