name       : neovim-qt
version    : 0.2.16.1
release    : 4
source     :
    - https://github.com/equalsraf/neovim-qt/archive/v0.2.16.1.tar.gz : 971d4597b40df2756b313afe1996f07915643e8bf10efe416b64cc337e4faf2a
license    : ISC
component  : editor
summary    : Neovim client library and GUI, in Qt5.
description: |
    Neovim client library and GUI, in Qt5.
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(msgpack)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - neovim
rundeps    :
    - neovim
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_MSGPACK=ON .
build      : |
    %make
install    : |
    %make_install
